### ISSUE TITLE
I cant get this to work

### ISSUE THREAD

**Issue by Oleafeon** [OptimoApps/statamic-rich-snippet#3]
Hi i was trying to use your plugin but i got an couple errors

I was not able to use this plugin in my project cause my project is 3.3 and php 8.1 can you please update this

after forking and updating myself i was not able to go to schema.org page in the cp cause the blueprint was looking for a container assets but i renamed my containers
![image](https://user-images.githubusercontent.com/20043831/195040118-f93bb545-3011-404d-9cef-51f7bd4c62e1.png)

also i got an error on the entries 
![image](https://user-images.githubusercontent.com/20043831/195040032-221682e7-b4dc-419d-8ae1-ea3650ec83d6.png)

**Comment by ssatz** [comment]
Hi,

Will take a look.

Best Regards,
Satz
